import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        Chart: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        URL: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        CustomEvent: 'readonly',
        Notification: 'readonly',
        Node: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        PerformanceObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        crypto: 'readonly',
        indexedDB: 'readonly',
        Image: 'readonly',
        process: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        Response: 'readonly',
        clients: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
    },
  },
  {
    ignores: ['eslint.config.js', 'node_modules/**', 'tests/**', '*.min.js'],
  },
];
