name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Jest configuration
        run: |
          echo "Checking Jest configuration..."
          node -e "console.log('Jest config loaded from package.json')" || echo "Jest config check failed"

      - name: Verify package.json scripts
        run: npm run

      - name: Start application server
        run: |
          npm start &
          sleep 5

      - name: Run automated tests
        run: npm test

      - name: Run detailed tests
        run: |
          echo "Available scripts:"
          npm run
          echo "Running test:detailed..."
          npm run test:detailed || {
            echo "test:detailed failed, trying alternative approach..."
            npm test -- --coverage --verbose --detectOpenHandles --forceExit
          }

      - name: Generate test results
        run: |
          echo '{"testResults": "completed", "timestamp": "'$(date -Iseconds)'"}' > test-results.json
          echo '{"detailedResults": "completed", "timestamp": "'$(date -Iseconds)'"}' > detailed-test-results.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.json
            detailed-test-results.json
            coverage/
            screenshot-*.png

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-screenshots
          path: '*.png'

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
