name: Keep Supabase Alive

on:
  schedule:
    # 毎日午前0時 (UTC) に実行
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動でも実行できるようにする

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET \
            "${{ secrets.SUPABASE_URL }}/rest/v1/exercises?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"